custom:
  bert_base_path: C:\Users\Aaron\Desktop\AI Stuff\Baldi_Discord_Bot\venv\Lib\site-packages\GPT_SoVITS\pretrained_models\chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: C:\Users\Aaron\Desktop\AI Stuff\Baldi_Discord_Bot\venv\Lib\site-packages\GPT_SoVITS\pretrained_models\chinese-hubert-base
  device: cuda
  is_half: true
  t2s_weights_path: C:\Users\Aaron\Desktop\AI Stuff\Baldi_Discord_Bot\models\BaldiMelonHeadV2\GPT_weights\BaldiMelonHeadV2-e10.ckpt
  version: v1
  vits_weights_path: C:\Users\Aaron\Desktop\AI Stuff\Baldi_Discord_Bot\models\BaldiMelonHeadV2\SoVITS_weights\BaldiMelonHeadV2_e8_s832.pth
default:
  bert_base_path: pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
  version: v1
  vits_weights_path: pretrained_models/s2G488k.pth
default_v2:
  bert_base_path: pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  version: v2
  vits_weights_path: pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
